models = [
    ("adding.1", 6),
    ("adding.2", 10),
    ("adding.3", 10),
	("adding.4", 11),
	("adding.5", 11),
	("adding.6", 11),
	("anderson.1", 8),
	("anderson.2", 3),
	("anderson.3", 5),  #timeout
	("anderson.4", 3),
	("anderson.5", 5),  #unsure
	("anderson.6", 4),
	("anderson.7", 5),  #unsure
	("anderson.8", 4),
	("at.1", 8),
	("at.2", 8),
	("at.3", 8),
	("at.4", 8),
	("at.5", 8),
	("at.6", 8),
	("at.7", 8),
	("bakery.1", 4),
	("bakery.2", 3),
	("bakery.3", 3),
	("bakery.4", 3),
    ("bakery.5", 3),
	("bakery.6", 3),
	("bakery.7", 4),
	("bakery.8", 3),
	("blocks.2", 8),
	("blocks.3", 8),
	("blocks.4", 8), #timeout
	("bopdp.1", 6),
	("bopdp.2", 6),
	("bopdp.3", 6),
	("bridge.1", 6),
	("bridge.2", 8),
	("bridge.3", 8),
	("brp.1", 3),
	("brp.2", 3),
	("brp.3", 5),
	("brp.4", 6),
	("brp.5", 6),
	("brp.6", 6),
	("brp2.1", 6),
	("brp2.2", 5),
	("brp2.3", 5),
	("brp2.4", 7),
	("brp2.5", 7),
	("brp2.6", 8),
	("cambridge.1", 16),
	("cambridge.2", 16),
	("cambridge.3", 16),
	("cambridge.4", 16),
	("cambridge.5", 16),
	("cambridge.6", 16),
	("cambridge.7", 16),
	("collision.1", 8),
	("collision.2", 8),
	("collision.3", 9),
	("collision.4", 9),
	("collision.5", 9),
	("collision.6", 10 ),# unsure, timeout
	("cyclic_scheduler.1", 2),
	("cyclic_scheduler.2", 2),
	("cyclic_scheduler.3", 2),
	("cyclic_scheduler.4", 2),
	("driving_phils.1", 16),
	("driving_phils.2", 16),
	("driving_phils.3", 16), #timeout
	("driving_phils.4", 16), #timeout
	("driving_phils.5", 16), #timeout
	("elevator.1", 3),
	("elevator.2", 2),
	("elevator.3", 3),
	("elevator.4", 3),
	("elevator.5", 4), #timeout
	("elevator2.1", 16),
	("elevator2.2", 4),
	("elevator2.3", 16),
	("elevator_planning.1", 8),
	("elevator_planning.2", 8),
	("elevator_planning.3", 8),
	("exit.1", 5),
	("exit.2", 4),
	("exit.3", 4),
	("exit.4", 5),
	("exit.5", 4),
	("extinction.1", 8),
	("extinction.2", 8),
	("extinction.3", 8),
	("extinction.4", 8),
	("firewire_link.1", 16),
	("firewire_link.2", 16),
	("firewire_link.3", 16),
	("firewire_link.4", 16),
	("firewire_link.5", 16),
	("firewire_link.6", 16),
	("firewire_link.7", 16),
	("firewire_tree.1", 4),
	("firewire_tree.2", 5),
	("firewire_tree.3", 5),
	("firewire_tree.4", 5),
	("firewire_tree.5", 6), #timeout
	("fischer.1", 8),
	("fischer.2", 8),
	("fischer.3", 8),
	("fischer.4", 8),
	("fischer.5", 8),
	("fischer.6", 8),
	("fischer.7", 8),
	("frogs.1", 5),
	("frogs.2", 3),
	("frogs.3", 5),
	("frogs.4", 7), #unsure, timeout
	("frogs.5", 7), #unsure, timeout
	("gear.1", 16),
	("gear.2", 16),
	("hanoi.1", 7),
	("hanoi.2", 7), #timeout
	("hanoi.3", 7), #unsure, timeout
	("hanoi.4", 7), #unsure, timeout
	("iprotocol.1", 3),
	("iprotocol.2", 3),
	("iprotocol.3", 3),
	("iprotocol.4", 4),
	("iprotocol.5", 4), #unsure, timeout
	("iprotocol.6", 4),
	("iprotocol.7", 4),
	("krebs.1", 5),
	("krebs.2", 6),
	("krebs.3", 6),
	("krebs.4", 6),
	("lamport.1", 8),
	("lamport.2", 8),
	("lamport.3", 8),
	("lamport.5", 8),
	("lamport.6", 8),
	("lamport.7", 8),
	("lamport.8", 8),
	("lamport_nonatomic.1", 4),
	("lamport_nonatomic.2", 4),
	("lamport_nonatomic.3", 4),
	("lamport_nonatomic.4", 4),
	("lamport_nonatomic.5", 4),
	("lann.1", 8),
	("lann.2", 8),
	("lann.3", 8),
	("lann.4", 8),
	("lann.5", 8),
	("lann.6", 8),
	("lann.7", 8),
	("lann.8", 8), #unsure, timeout
	("leader_election.1", 7),
	("leader_election.2", 7),
	("leader_election.3", 7),
	("leader_election.4", 7),
	("leader_election.5", 7),
	("leader_election.6", 7),
	("leader_filters.1", 4),
	("leader_filters.2", 4),
	("leader_filters.3", 4),
	("leader_filters.4", 4),
	("leader_filters.5", 4),
	("leader_filters.6", 4),
	("leader_filters.7", 4),
	("lifts.1", 6),
	("lifts.2", 6),
	("lifts.3", 6),
	("lifts.4", 6),
	("lifts.5", 6),
	("lifts.6", 6),
	("lifts.7", 6),
	("lifts.8", 6), #unsure, timeout
	("loyd.1", 3),
	("loyd.2", 4),
	("loyd.3", 5), #unsure, timeout
	("lup.1", 3),
	("lup.2", 3),
	("lup.3", 4),
	("lup.4", 4),
	("mcs.1", 8),
	("mcs.2", 8),
	("mcs.3", 8),
	("mcs.4", 8),
	("mcs.5", 8), #unsure, timeout
	("mcs.6", 8),
	("msmie.1", 4),
	("msmie.2", 4),
	("msmie.3", 4),
	("msmie.4", 4),
	("needham.1", 12),
	("needham.2", 12),
	("needham.3", 12),
	("needham.4", 12),
	("peg_solitaire.1", 4),
	("peg_solitaire.2", 6), #timeout
	("peg_solitaire.3", 6), #unsure, timeout
	("peg_solitaire.4", 5), #unsure, timeout
	("peg_solitaire.5", 5),
	("peg_solitaire.6", 6), #unsure, timeout
	("peterson.1", 3),
	("peterson.2", 3),
	("peterson.3", 3),
	("peterson.4", 3),
	("peterson.5", 3),
	("peterson.6", 3),
	("peterson.7", 3),
	("pgm_protocol.1", 4),
	("pgm_protocol.2", 4),
	("pgm_protocol.3", 4),
	("pgm_protocol.4", 4),
	("pgm_protocol.5", 4),
	("pgm_protocol.6", 4), #unsure, timeout
	("pgm_protocol.7", 4),
	("pgm_protocol.8", 4), #unsure, timeout
	("phils.1", 2),
	("phils.2", 3),
	("phils.3", 2),
	("phils.4", 3),
	("phils.5", 2),
	("phils.6", 2),
	("phils.7", 4),
	("phils.8", 2),
    ("plc.1", 16), #dve2C not found... (segfault),
    ("plc.2", 16),
    ("plc.3", 16),
    ("plc.4", 16),
	("pouring.1", 5),
	("pouring.2", 4),
	#("pouring.3", 5),
	#("pouring.4", 5),
	#("pouring.5", 5),
	("production_cell.1", 8),
	("production_cell.2", 8),
	("production_cell.3", 8),
	("production_cell.4", 8),
	("production_cell.5", 8),
	("production_cell.6", 8), #unsure, timeout
	("protocols.1", 2),
	("protocols.2", 2),
	("protocols.3", 3),
	("protocols.4", 5),
	("protocols.5", 6),
	("public_subscribe.1", 8),
	("public_subscribe.2", 8),
	("public_subscribe.3", 8),
	("public_subscribe.4", 8),
	("public_subscribe.5", 8), #unsure, timeout
	("reader_writer.1", 4),
	("reader_writer.2", 4),
	("reader_writer.3", 4),
	("resistance.1", 16),
	("resistance.2", 16),
	("rether.1", 4),
	("rether.2", 4),
	("rether.3", 4),
	("rether.4", 4), #unsure
	("rether.5", 4), #unsure, timeout
	("rether.6", 4), #unsure, timeout
	("rether.7", 4), #unsure, timeout
	("rushhour.1", 3),
	("rushhour.2", 3),
	("rushhour.3", 3), #unsure, timeout
	("rushhour.4", 3), #unsure, timeout
	("schedule_world.1", 8),
	("schedule_world.2", 8),
	("schedule_world.3", 8),
	("sokoban.1", 3),
	("sokoban.2", 4),
	("sokoban.3", 5), #unsure, timeout
	("sorter.1", 4),
	("sorter.2", 4),
	("sorter.3", 4),
	("sorter.4", 8),
	("sorter.5", 4),
	("synapse.1", 16),
	("synapse.2", 16),
	("synapse.3", 16),
	("synapse.4", 16),
	("synapse.5", 16),
	("synapse.6", 16),
	("synapse.7", 16),
	("szymanski.1", 4),
	("szymanski.2", 4),
	("szymanski.3", 4),
	("szymanski.4", 4),
	("szymanski.5", 4),
	("telephony.1", 8),
	("telephony.2", 8),
	("telephony.3", 8),
	("telephony.4", 8),
	("telephony.5", 8), #unsure, timeout
	("telephony.6", 8), #unsure, timeout
	("telephony.7", 8),
	("telephony.8", 8), #unsure, timeout
    ("train-gate.1", 16), #unsure
    ("train-gate.2", 16), #unsure
    ("train-gate.3", 16), #unsure
    ("train-gate.4", 16), #unsure
    ("train-gate.5", 16), #unsure
    ("train-gate.6", 16), #unsure
    ("train-gate.7", 16), #unsure
]




